services:
    reactfrontend:
        build: ./react-app
        environment:
            REACT_APP_GPT_URL: localhost:9000
            REACT_APP_GPT_PROTOCOL: http
        ports:
            - "3000:3000"
        links: 
            - nodebackend:backend
        depends_on:
            - db
            - nodebackend
    nodebackend:
        build: ./Node-backend
        environment:
            MONGODB_URI: mongodb://db:27017/chatdb
            PORT: 9000
            url: nodebackend
            OPENAI_API_KEY: 
        ports:
            - "9000:9000"   
        depends_on:
            - db
    db:
        volumes:
            - chat_db:/data/db
        image: mongo:latest
        environment:
            MONGO_INITT_DATABASE: chatdb
        ports:
            - "27017:27017" 
volumes:
    chat_db: